route:
    receiver: 'slack'
    group_wait: 5s
    group_interval: 5s

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '@tfabremoschetti'
            api_url: 'https://hooks.slack.com/services/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'
