sudo: required
language: java

cache:
  directories:
    - $HOME/.m2

services:
  - docker
  - maven

before_install:
  - docker version

install: true

script:
  - echo $USER
  - pushd cu-services && make tomcat && make mysql && popd
  - pushd cu-compose && cp .env.local.xip.io .env && ./reset-dev.sh -y && popd
  - docker ps -a
  - mvn install -Plocal
