sudo: required
language: java

services:
  - docker
  - maven

before_install:
  - docker version

install: true

script:
- echo $USER
- cd /home/travis/build/Treeptik/cloudunit/ && ./update-docker.sh
- docker version
- cd cu-services && make tomcat && make mysql
- cp /home/travis/build/Treeptik/cloudunit/cu-compose/.env.local.xip.io /home/travis/build/Treeptik/cloudunit/cu-compose/.env
- cd /home/travis/build/Treeptik/cloudunit/cu-compose && ./reset-dev.sh -y
- cd /home/travis/build/Treeptik/cloudunit && mvn install -DskipTests -DskipITs
- mvn verify -Plocal
#- cd /home/travis/build/Treeptik/cloudunit/cu-compose &&  ./cu-docker-compose.sh with-elk
#- docker ps -a
#- cd /home/travis/build/Treeptik/cloudunit/cu-manager && mvn test "-Dtest=*Tomcat8ApplicationControllerTestIT"
