version: "2"

services:


  db:
    build:
      context: ./cu-mattermost/db
    restart: unless-stopped
    volumes:
      - mattermost-dbdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost

  app:
    build:
      context: ./cu-mattermost/app
    restart: unless-stopped
    volumes:
      - mattermost-appconfig:/mattermost/config:rw
      - mattermost-appdata:/mattermost/data:rw
      - mattermost-logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
    depends_on:
      - db

  web:
    build:
      context: ./cu-mattermost/web
    restart: unless-stopped
    environment:
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.frontend.entryPoints=https"
      - "traefik.backend=cu-mattermost"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${CU_MATTERMOST_DOMAIN}"
    depends_on:
      - app

networks:
  default:
    external:
      name: skynet

volumes:
  mattermost-logs:
  mattermost-appdata:
  mattermost-appconfig:
  mattermost-dbdata: