version: '2'
services:

  mongo:
      container_name: cu-mongo
      env_file: .env
      image: mongo:3.4.2
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db
        - mongo-config:/data/configdb
      labels:
        - "traefik.enable=false"

  traefik:
      container_name: cu-traefik
      env_file: .env
      image: traefik
      command: --web --docker --docker.domain=${CU_DOMAIN} --logLevel=DEBUG --docker.exposedbydefault=true --docker.watch=true
      ports:
        - "80:80"
        - "443:443"
        - "9090:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./cu-traefik/traefik.toml:/traefik.toml
        - ./cu-traefik/certs:/certs
      labels:
        - "traefik.enable=false"

  rabbitmq:
    container_name: cu-mq
    image: rabbitmq:3.6.8-alpine
    ports:
      - "5672:5672"
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"
    labels:
      - "traefik.enable=false"

volumes:
  mongo-data:
  mongo-config:
  rabbitmq-data:
  traefik-certs:
