version: '2.1'
services:
  postgres:
    image: postgres:9.6.3-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_USER=clair
      - POSTGRES_DB=clair
    volumes:
      - postgresdata:/var/lib/postgresql/data

  clair:
    image: quay.io/coreos/clair:v2.0.0
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - clairtmp:/tmp:rw
      - ./clair_config:/config:ro
    command: [--log-level=debug, -config, /config/config.yaml]

  clairctl:
    container_name: clairctl
    image: jgsqware/clairctl:latest
    restart: unless-stopped
    depends_on:
      clair:
        condition: service_started
    environment:
      - DOCKER_API_VERSION=1.29
    volumes:
      - ./reports:/reports:rw
      - clairctltmp:/tmp:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    user: root

volumes:
  postgresdata:
  clairtmp:
  clairctltmp:
