---
spring:
  profiles: dev
  data:
    mongodb:
      host: 192.168.50.4
      database: cu-manager-domain
  rabbitmq:
    host: 192.168.50.4
server:
  port: 8080
logging:
  level:
    org.springframework.data: debug
cloudunit:
  orchestrator:
    base-uri: http://localhost:8081/