---
spring:
  profiles: vagrant
  data:
    mongodb:
      host: 192.168.50.4
      database: cu-docker-orchestrator
  rabbitmq:
    host: 192.168.50.4
server:
  port: 8081
docker:
  client:
    endpointMode: HTTP
    uri: http://192.168.50.4:4243
logging:
  level:
    fr.treeptik: debug
    org.springframework.cloud: debug
    org.springframework.integration: debug
cloudunit:
  domain-name: 192.168.50.4.xip.io
---
spring:
  profiles: local
  data:
    mongodb:
      host: localhost
      database: cu-docker-orchestrator
    rabbitmq:
      host: localhost
server:
  port: 8081
docker:
  client:
    endpointMode: SOCKET
logging:
  level:
    fr.treeptik: debug
    org.springframework.cloud: debug
    org.springframework.integration: debug
cloudunit:
  domain-name: 127.0.0.1.xip.io
---
spring:
  profiles: production
  data:
    mongodb:
      host: cu-mongo
      database: cu-docker-orchestrator
    rabbitmq:
      host: cu-rabbitmq
server:
  port: 8080
docker:
  client:
    endpointMode: SOCKET
logging:
  level:
    fr.treeptik: info
