---
spring:
  profiles: dev
  data:
    mongodb:
      host: 192.168.50.4
      database: cu-docker-orchestrator
  rabbitmq:
    host: 192.168.50.4
server:
  port: 8081
docker:
  client:
    endpointMode: HTTP
    uri: http://192.168.50.4:4243
logging:
  level:
    fr.treeptik: debug