---
spring:
  profiles: dev
zuul:
  addProxyHeaders: false
  routes:
    applications:
      url: http://localhost:8080/applications
    containers:
      url: http://localhost:8081/containers
    images:
      url: http://localhost:8081/images
server:
  port: 9000
---
spring:
  profiles: production
zuul:
  addProxyHeaders: false
  routes:
    applications:
      url: http://cu-domain:8080/applications
    containers:
      url: http://cu-orchestrator:8081/containers
    images:
      url: http://cu-orchestrator:8081/images
server:
  port: 9000
