version: '2'
services:

  postgres:
    container_name: clair-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password

  clair:
    container_name: clair-core
    image: quay.io/coreos/clair:latest
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    links:
      - postgres
    volumes:
      - clair_tmp:/tmp
      - ./clair_config:/config
    command: [-config, /config/config.yaml]

  registry:
    container_name: registry
    image: registry:2
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry

volumes:
  clair_tmp:
  clair_config:
  registry_data: